import {
  BarChart3, BookOpen, Building2, CheckCircle2, GraduationCap, Layers3,
  MessageSquare, MonitorSmartphone, Palette, School, Sparkles, Target, Users, UserRound,
} from "lucide-react";
import { DemoScreenshot } from "@/components/demo/DemoScreenshot";
import { CTASection } from "@/components/sections/CTASection";
import { PageHero } from "@/components/sections/PageHero";
import { SectionHeading } from "@/components/sections/SectionHeading";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("Edora Education OS", "Explore the complete Edora Education OS for publishers, institutions, educators, learners, mentors and families.", "/platform");

const layers = [
  [BookOpen, "Content Layer", "Books, resources, videos and question banks", ["Digital books", "Resources", "Question banks"]],
  [School, "Academic Layer", "Years, classes, sections, courses, batches and assignments", ["Academic structures", "Batches", "Assignments"]],
  [GraduationCap, "Learning Layer", "Reading, revision, practice, assessments and mentoring", ["Practice", "Assessments", "Mentoring"]],
  [BarChart3, "Intelligence Layer", "Reports, analytics, gaps, remedials and grounded AI", ["Reports", "Gap analysis", "Grounded AI"]],
  [MessageSquare, "Communication Layer", "Discussion, live classes, announcements and calendar — upcoming", ["Announcements", "Calendar", "Coming next"]],
  [MonitorSmartphone, "Experience Layer", "Publisher, organization, teacher, learner, mentor and parent portals", ["Role-based portals", "White-label", "Responsive"]],
] as const;

const experiences = [
  { id: "publisher-platform", icon: BookOpen, title: "Publisher Platform", audience: "Educational publishers modernizing books, resources and institutional relationships.", overview: "A secure publisher workspace for managing digital content, connected schools, feature access and branded services.", features: ["Digital books", "Teacher resources", "School approvals", "Publisher analytics", "Feature controls", "Brand management"], benefits: ["Extend publishing services digitally", "Protect approved content", "Build stronger school relationships"], image: "publisher-dashboard.webp", query: "publisher" },
  { id: "school-platform", icon: School, title: "School Platform", audience: "Schools coordinating academic structures, educators, learners and approved resources.", overview: "One organized environment for school setup, user management, book access and learning visibility.", features: ["Academic years", "Classes and sections", "Teachers and students", "Subject assignments", "Book approvals", "Reports"], benefits: ["Reduce fragmented workflows", "Keep roles and access clear", "Connect academics with learning"], image: "school-dashboard.webp", query: "school" },
  { id: "coaching-platform", icon: Target, title: "Coaching Platform", audience: "Coaching institutes running structured courses, batches, faculty and assessments.", overview: "A growth-ready platform designed to bring coaching operations and learner experiences together.", features: ["Courses and batches", "Faculty access", "Assignments", "Assessments", "Student portal", "Mentor workflows", "Live classes — planned", "Discussion rooms — planned"], benefits: ["Organize programs consistently", "Give learners one clear workspace", "Prepare for richer online delivery"], image: "school-dashboard.webp", query: "coaching" },
  { id: "academy-platform", icon: Building2, title: "Academy Platform", audience: "Academies delivering focused, branded learning programs directly to learners.", overview: "A configurable foundation for onboarding learners, shaping learning plans and tracking progress.", features: ["Learner onboarding", "Program structures", "Individual plans", "Assessments", "Mentors", "Analytics"], benefits: ["Launch branded programs", "Support individual goals", "Grow without rebuilding the platform"], image: "school-dashboard.webp", query: "academy" },
  { id: "teacher-workspace", icon: UserRound, title: "Teacher Workspace", audience: "Teachers who need approved content, practical tools and learner insight.", overview: "A focused teaching environment that brings assigned books, resources, assessments and support workflows together.", features: ["Assigned books", "Teaching resources", "Question support", "Student monitoring", "Reports", "Grounded Teacher AI"], benefits: ["Spend less time finding resources", "Act on learner needs earlier", "Keep AI within approved content"], image: "teacher-dashboard.webp", query: "teacher" },
  { id: "student-experience", icon: GraduationCap, title: "Student Experience", audience: "Learners studying from approved books and structured academic programs.", overview: "A guided learning home for reading, revision, practice, assessment and personalized support.", features: ["Books and reader", "Revision Hub", "Practice", "Assessments", "Learning Assistant", "Gap and remedial insight"], benefits: ["Know what to learn next", "Keep study tools connected", "Receive support in the right context"], image: "student-dashboard.webp", query: "student" },
  { id: "parent-dashboard", icon: Users, title: "Parent Dashboard", audience: "Parents and guardians supporting linked learners.", overview: "An appropriate family view of released progress information, assessments and available support.", features: ["Linked children", "Progress summaries", "Released results", "Support areas", "Remedial progress", "Mentor overview"], benefits: ["Understand progress clearly", "Support learning with context", "Stay connected without information overload"], image: "parent-dashboard.webp", query: "parent" },
  { id: "mentor-dashboard", icon: Sparkles, title: "Mentor Dashboard", audience: "Mentors guiding assigned learners through gaps and remedial work.", overview: "A dedicated workspace for reviewing learner needs, recording notes and following support progress.", features: ["Assigned learners", "Gap review", "Remedial monitoring", "Mentor notes", "Progress summaries", "Support sessions"], benefits: ["Focus on assigned learners", "Make support evidence-led", "Track follow-through over time"], image: "mentor-dashboard.webp", query: "mentor" },
  { id: "white-label-platform", icon: Palette, title: "White-label Platform", audience: "Publishers and learning organizations that need a platform aligned with their own identity.", overview: "Configurable branding and feature controls on a shared, secure Edora foundation.", features: ["Organization branding", "Independent tenants", "Role-based portals", "Feature configuration", "Content entitlements", "Modular growth"], benefits: ["Present a coherent brand", "Keep organizations separated", "Adopt only the capabilities required"], image: "super-admin-dashboard.webp", query: "platform" },
] as const;

export default function PlatformPage() {
  return <><PageHero eyebrow="Edora Education OS" title="One Operating System for Modern Education" description="Connect content, academic operations, learning and intelligence through a configurable platform built around real education workflows." accent="sky" />
    <section className="section section-soft-blue"><div className="container"><SectionHeading eyebrow="Platform architecture" title="Six Layers. One Connected Experience." description="Each layer has a clear purpose, while the platform brings them together for simpler day-to-day work." /><div className="architecture">{layers.map(([Icon, title, description, chips]) => <article className="architecture-layer" key={title}><span className="layer-number"><Icon size={22} aria-hidden="true" /></span><h3>{title}</h3><div><p>{description}</p><div className="chip-row">{chips.map((chip) => <span key={chip}>{chip}</span>)}</div></div></article>)}</div></div></section>
    <section className="section section-white"><div className="container split"><div><SectionHeading eyebrow="A practical foundation" title="Built to Fit Your Education Ecosystem" description="EEOS balances organization-level flexibility with a consistent, secure foundation." /><div className="platform-visual"><Layers3 aria-hidden="true" /><strong>One secure foundation</strong><span>Flexible experiences for every organization</span></div></div><div className="foundation-list">{["Multi-tenant and white-label", "Role-based experiences", "Secure educational content", "Modular feature controls", "Designed for publishers and institutions"].map((title) => <article className="large-point" key={title}><span><CheckCircle2 size={25} /></span><div><h3>{title}</h3><p>Clear controls and purposeful experiences support each organization without exposing unrelated data or tools.</p></div></article>)}</div></div></section>
    <section className="platform-experiences"><div className="container platform-experience-heading"><SectionHeading eyebrow="Complete role experiences" title="One Platform, Distinct Experiences" description="Explore what each workspace is for, why it matters and how it supports day-to-day education work." /></div>{experiences.map((item) => { const Icon = item.icon; return <article className="platform-experience" id={item.id} key={item.id}><div className="container platform-experience-grid"><div className="platform-experience-media"><DemoScreenshot src={`/images/demo/${item.image}`} role={item.title} alt={`Edora Education OS ${item.title} preview`} caption={`${item.title} platform preview`} /></div><div className="platform-experience-copy"><p className="demo-role-badge"><Icon size={17} aria-hidden="true" />{item.title}</p><h2>{item.title}</h2><p><strong>Who it is for:</strong> {item.audience}</p><p><strong>Overview:</strong> {item.overview}</p><h3>Key features</h3><ul className="platform-feature-list">{item.features.map((feature) => <li key={feature}><CheckCircle2 size={17} />{feature}</li>)}</ul><h3>Key benefits</h3><ul className="platform-benefit-list">{item.benefits.map((benefit) => <li key={benefit}>{benefit}</li>)}</ul></div></div></article>; })}</section>
    <CTASection title="Ready to Modernize Your Education Platform?" description="Book a guided conversation around your organization, users, content and growth plans." />
  </>;
}
