import { BarChart3, BookOpen, CheckCircle2, GraduationCap, Layers3, MessageSquare, MonitorSmartphone, School } from "lucide-react";
import { CTASection } from "@/components/sections/CTASection";
import { PageHero } from "@/components/sections/PageHero";
import { SectionHeading } from "@/components/sections/SectionHeading";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("Edora Education OS", "Explore the six connected layers of Edora Education OS for publishers, institutions, educators and learners.", "/platform");
const layers = [
  [BookOpen, "Content Layer", "Books, resources, videos and question banks", ["Digital books", "Resources", "Question banks"]],
  [School, "Academic Layer", "Years, classes, sections, courses, batches and assignments", ["Academic structures", "Batches", "Assignments"]],
  [GraduationCap, "Learning Layer", "Reading, revision, practice, assessments and mentoring", ["Practice", "Assessments", "Mentoring"]],
  [BarChart3, "Intelligence Layer", "Reports, analytics, gaps, remedials and grounded AI", ["Reports", "Gap analysis", "Grounded AI"]],
  [MessageSquare, "Communication Layer", "Discussion, live classes, announcements and calendar — upcoming", ["Announcements", "Calendar", "Coming next"]],
  [MonitorSmartphone, "Experience Layer", "Publisher, organization, teacher, learner, mentor and parent portals", ["Role-based portals", "White-label", "Responsive"]],
] as const;
const foundations = [["Multi-tenant and white-label", "Independent spaces and configurable branded experiences for every organization."], ["Role-based experiences", "Focused journeys that give users the capabilities appropriate to their work."], ["Secure educational content", "Content access follows organizational permissions, roles and entitlements."], ["Modular feature controls", "Activate the capabilities each organization needs as programs evolve."], ["Designed for publishers and institutions", "A shared foundation that respects distinct operating models and learning goals."]];

export default function PlatformPage() { return <><PageHero eyebrow="Edora Education OS" title="One Operating System for Modern Education" description="Connect content, academic operations, learning and intelligence through a configurable platform built around real education workflows." cta={{ label: "Book a Platform Demo", href: "/contact?interest=demo" }} accent="sky" /><section className="section section-soft-blue"><div className="container"><SectionHeading eyebrow="Platform architecture" title="Six Layers. One Connected Experience." description="Each layer has a clear purpose, while the platform brings them together for simpler day-to-day work." /><div className="architecture">{layers.map(([Icon, title, description, chips]) => <article className="architecture-layer" key={title}><span className="layer-number"><Icon size={22} aria-hidden="true" /></span><h3>{title}</h3><div><p>{description}</p><div className="chip-row">{chips.map((chip) => <span key={chip}>{chip}</span>)}</div></div></article>)}</div></div></section><section className="section section-white"><div className="container split"><div><SectionHeading eyebrow="A practical foundation" title="Built to Fit Your Education Ecosystem" description="EEOS balances organization-level flexibility with a consistent, secure foundation." /><div className="platform-visual"><Layers3 aria-hidden="true" /><strong>One secure foundation</strong><span>Flexible experiences for every organization</span></div></div><div className="foundation-list">{foundations.map(([title, description]) => <article className="large-point" key={title}><span><CheckCircle2 size={25} /></span><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></div></section><CTASection title="See Edora Education OS in Context" description="Explore how the platform can be configured around your content, teams, learners and programs." primary="Book a Platform Demo" /></> }
