import { Lightbulb, Target } from "lucide-react";
import { CTASection } from "@/components/sections/CTASection";
import { PageHero } from "@/components/sections/PageHero";
import { SectionHeading } from "@/components/sections/SectionHeading";
import { pageMetadata } from "@/lib/metadata";
import { siteConfig } from "@/lib/site-config";

export const metadata = pageMetadata("About Edora Learning", "Meet Edora Learning, an education technology company building secure, intelligent and easy-to-use digital solutions.", "/about");
const values = [["Learner first", "Design decisions begin with meaningful learner outcomes."], ["Simplicity", "Complex education workflows should feel clear and manageable."], ["Trust", "We build with responsible controls, transparency and respect."], ["Responsible innovation", "New technology must serve a defined educational purpose."], ["Quality", "Thoughtful details create reliable, useful experiences."], ["Partnership", "The strongest solutions grow from listening and working together."]];

export default function AboutPage() { return <><PageHero eyebrow="About Edora Learning" title="Built From Education Experience" description="Edora Learning Pvt. Ltd. is an education technology company building secure, intelligent and easy-to-use digital solutions for the education ecosystem." accent="orange" /><section className="section section-soft-yellow"><div className="container grid-2"><article className="mission-card"><span><Target /></span><SectionHeading eyebrow="Our mission" title="Simplify and Strengthen Education" description="To simplify and strengthen education through intelligent technology that helps institutions, educators and learners succeed." /></article><article className="vision-card"><span><Lightbulb /></span><SectionHeading eyebrow="Our vision" title="A Trusted Education Operating System" description="To build a trusted Education Operating System that connects every part of the learning ecosystem." /></article></div></section><section className="section section-white"><div className="container"><SectionHeading eyebrow="Our values" title="Principles That Guide the Platform" /><div className="grid-3">{values.map(([title, description]) => <article className="value-card" key={title}><h3>{title}</h3><p>{description}</p></article>)}</div></div></section><section className="section section-soft-blue"><div className="container split"><div><SectionHeading eyebrow="Our story" title="Shaped by Practical Education Needs" /><div className="story-steps"><div className="story-step"><span>01</span><div><h3>Experience in education</h3><p>Edora began with real work in educational publishing and curriculum development.</p></div></div><div className="story-step"><span>02</span><div><h3>A practical need</h3><p>That experience revealed how deeply content, institutions, educators and learners need to work together.</p></div></div><div className="story-step"><span>03</span><div><h3>A connected platform</h3><p>Edora Education OS brings that practical perspective to secure, adaptable education technology.</p></div></div></div></div><div><p className="eyebrow">Leadership</p><article className="leader-card"><div className="leader-avatar" aria-label="Vikas Kumar Sharma initials">VKS</div><h3>Vikas Kumar Sharma</h3><p className="role">Founder &amp; Director</p><p>Curriculum developer, writer, editor and education entrepreneur focused on building practical solutions for publishers, institutions, educators and learners.</p></article></div></div></section><CTASection title="Better Education Experiences" description={`Edora Learning builds practical education technology around the needs of institutions, educators and learners. Contact information: ${siteConfig.email}.`} /></> }
