import Link from "next/link";
import { ArrowRight, BookOpen, Building2, GraduationCap, School, Target, Users } from "lucide-react";
import { PageHero } from "@/components/sections/PageHero";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("Education Technology Solutions", "Solutions for publishers, schools, coaching institutes, academies, educators, learners and families.", "/solutions");
const solutions = [
  { id: "publishers", icon: BookOpen, title: "Publishers", challenge: "Modernize content and school relationships without losing brand ownership or control.", solution: "Edora gives publishers a white-label foundation for digital catalogues, approved learning content and educator services.", benefits: ["Digital catalogue", "Book knowledge system", "Teacher resources", "School relationships", "Publisher AI", "White-label platform"], cta: "Request Publisher Demo", query: "publisher" },
  { id: "schools", icon: School, title: "Schools", challenge: "Bring fragmented academic, teaching and learning workflows into a coherent experience.", solution: "Connect school structures, approved resources and role-specific learning tools through one secure platform.", benefits: ["Academic setup", "Teacher and student management", "Approved books", "Learning tools", "Reports", "Parent access"], cta: "Discuss School Solution", query: "school" },
  { id: "coaching", icon: Target, title: "Coaching Institutes", challenge: "Coordinate courses, batches, educators and learners while preparing for richer online programs.", solution: "EEOS is designed to support coaching workflows today and is roadmap-ready for expanded collaboration experiences.", benefits: ["Courses and batches", "Faculty and learner access", "Own books and notes", "Practice and assessment", "Mentors", "Future live classes and discussion rooms"], cta: "Explore Coaching Solution", query: "coaching" },
  { id: "academies", icon: Building2, title: "Academies", challenge: "Deliver focused, branded programs that adapt to individual learner goals.", solution: "Launch structured learning journeys with mentor support and intelligence designed around measurable progress.", benefits: ["Direct learner onboarding", "Individual learning plans", "Mentors", "AI support", "Assessment", "Analytics"], cta: "Build an Academy", query: "academy" },
  { id: "educators", icon: GraduationCap, title: "Educators", challenge: "Find the right approved material and act on learner needs without adding administrative burden.", solution: "Give educators practical resources, grounded assistance and a clearer view of learner progress.", benefits: ["Approved books and resources", "Teaching support", "Question paper generation", "Student monitoring"], cta: "Talk to Edora", query: "general" },
  { id: "learners", icon: Users, title: "Learners and Families", challenge: "Make learning support understandable, relevant and connected to approved academic material.", solution: "Create a guided experience for study, practice, assessment and progress visibility—supported by appropriate family access.", benefits: ["Books", "Revision", "Practice", "AI support", "Assessments", "Progress insights"], cta: "Talk to Edora", query: "general" },
];

export default function SolutionsPage() { return <><PageHero eyebrow="Solutions" title="Technology Designed Around Real Education Needs" description="One adaptable foundation. Purposeful experiences for every organization and learner it serves." accent="yellow" /><div>{solutions.map(({ icon: Icon, ...item }) => <section className="solution-section" id={item.id} key={item.id}><div className="container solution-detail"><div><span className="solution-page-icon"><Icon aria-hidden="true" /></span><p className="challenge">Main challenge</p><h2>{item.title}</h2><p>{item.challenge}</p><h3 className="solution-approach">The Edora approach</h3><p>{item.solution}</p><div className="button-row"><Link className="button button-primary" href={`/contact?interest=${item.query}`}>{item.cta}<ArrowRight size={18} /></Link></div></div><div className="benefit-list">{item.benefits.map((benefit) => <div key={benefit}>{benefit}</div>)}</div></div></section>)}</div></> }
