import { BarChart3, Bot, ClipboardCheck, GraduationCap, ShieldCheck } from "lucide-react";
import { CTASection } from "@/components/sections/CTASection";
import { FeatureCard } from "@/components/sections/FeatureCard";
import { PageHero } from "@/components/sections/PageHero";
import { SectionHeading } from "@/components/sections/SectionHeading";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("Edora AI", "Education intelligence grounded in approved content, with role controls, human oversight and age-appropriate learner experiences.", "/ai");
const areas = [[Bot, "Teacher AI", "Develop teaching and assessment material grounded in the approved resources available to an educator."], [GraduationCap, "Student Learning Assistant", "Offer chapter-focused explanations, guided revision and support within clearly defined learning boundaries."], [BarChart3, "Learning Analytics", "Use relevant learning and assessment signals to help educators understand progress and areas for support."], [ClipboardCheck, "Assessment Intelligence", "Support question creation, assessment review, gap identification and appropriate remedial pathways."]] as const;
const principles = [["Approved-source grounding", "Responses are anchored to structured educational resources authorized for the user."], ["Clear scope", "Every AI workflow has a defined educational purpose and clear boundaries."], ["Privacy and tenant isolation", "Organization and user contexts remain separated through controlled access."], ["Validated outputs", "Important workflows include checks and review patterns appropriate to their use."], ["Human oversight", "Educators remain in control wherever professional judgment is needed."], ["No unrestricted learner chatbot", "Student experiences are age-appropriate, guided and limited to approved learning contexts."]];

export default function AIPage() { return <><div className="ai-hero"><PageHero eyebrow="Edora AI" title="Intelligence Grounded in Education" description="A provider-neutral foundation designed around approved content, clear roles, responsible controls and separate educator and learner workflows." cta={{ label: "See Edora AI in Action", href: "/demo#ai" }} accent="blue" /></div><section className="section section-ai ai-page-section"><div className="container"><SectionHeading eyebrow="Purpose-built workflows" title="AI That Supports the Work of Learning" description="Edora AI focuses intelligence where it can make education clearer, more relevant and more actionable." /><div className="grid-2 feature-grid ai-feature-grid">{areas.map(([icon, title, description]) => <FeatureCard key={title} icon={icon} title={title} description={description} />)}<FeatureCard icon={ShieldCheck} title="Responsible AI" description="Grounded, role-aware workflows with clear boundaries and human oversight where professional judgment matters." /></div></div></section><section className="section section-soft-yellow"><div className="container"><SectionHeading eyebrow="Responsible AI principles" title="Designed with Boundaries, Control and Trust" description="Human review is built in where appropriate, while roles and entitlements shape every experience." /><div className="principles">{principles.map(([title, description]) => <article className="principle" key={title}><h3>{title}</h3><p>{description}</p></article>)}</div></div></section><CTASection title="Explore Responsible Education AI" description="See how grounded intelligence can support your educators and learners within an approved, controlled learning environment." primary="Request an AI Demo" primaryHref="/contact?interest=ai" secondary="Talk to Our Team" secondaryHref="/contact?interest=ai" /></> }
